---
- name: Install WireGuard
  apt:
    pkg:
    - wireguard
    state: present
  when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

- name: Enable WireGuard
  service: name="wg-quick@{{ wireguard_iface }}" enabled=yes
  when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

- name: Unlink old private key
  file:
    path: "/etc/wireguard/private_{{ wireguard_iface }}"
    state: absent
  when: rotate_keys is true

- name: Generate private key or use existing
  shell: "umask 0077; cat /etc/wireguard/private_{{ wireguard_iface }} 2>/dev/null || wg genkey | tee /etc/wireguard/private_{{ wireguard_iface }}"
  register: wireguard_genkey

- set_fact:
    private_key: "{{ wireguard_genkey.stdout }}"

- name: Generate public key
  shell: "echo {{ private_key }} | wg pubkey"
  register: wireguard_pubkey

- set_fact:
    public_key: "{{ wireguard_pubkey.stdout }}"
