---
- name: Create WireGuard directory
  file:
    path: /etc/wireguard
    owner: root
    group: root
    mode: 0600
    state: directory

# read existing defined listening port or generate random one.
- include_tasks: read_config.yml
  when: wireguard_peers[ansible_hostname].port is not defined

- name: Configure WireGuard
  template:
    src: "wireguard.conf.j2"
    dest: "/etc/wireguard/{{ wireguard_iface }}.conf"
    mode: 0600 
    owner: root
    group: root
  notify: restart wireguard
